Assignment 3

In [1]:
import numpy as np

In [2]:
# Ans 1:
arr = np.array(range(2,51,3))
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [3]:
# Ans 2:
#take 5 user input and covert to np arrays
user_inp = np.array(list(map(int,input().split()[:5])))
user_inp2 = np.array(list(map(int,input().split()[:5])))
#concatenate
arr = np.concatenate( (user_inp,user_inp2) )
print(arr)
arr.sort()
print(arr)

5 7 8 9 6 1 2
3 5 7 9 1 6 8
[5 7 8 9 6 3 5 7 9 1]
[1 3 5 5 6 7 7 8 9 9]


In [4]:
# Ans 3:
arr = np.arange(24).reshape(4,6)
print(arr.shape)
print(arr.size)

(4, 6)
24


In [5]:
# Ans 4:
arr = np.arange(7,12)
print(arr)
print(arr.shape)
print()
arr = np.expand_dims(arr,1)
print(arr)
print(arr.shape)

[ 7  8  9 10 11]
(5,)

[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(5, 1)


In [6]:
# Ans 5:
a = np.array([[2, 3], [5, 6]])
b = np.array([[400,7], [800,9]])
print(a, end = '\n \n')
print(b, end = '\n \n')
#vertical stack
print(np.vstack( (a,b) ))
print()
#horizontal stack
print(np.hstack( (a,b) ))

[[2 3]
 [5 6]]
 
[[400   7]
 [800   9]]
 
[[  2   3]
 [  5   6]
 [400   7]
 [800   9]]

[[  2   3 400   7]
 [  5   6 800   9]]


In [7]:
# Ans 6:
arr = np.array([1,2,3,4,4,3,7,8,8,8,7,3,1])
(unique, counts) = np.unique(arr, return_counts=True)
np.asarray((unique, counts)).T

array([[1, 2],
       [2, 1],
       [3, 3],
       [4, 2],
       [7, 2],
       [8, 3]])